### PR TITLE
Market Cow Price and Number of Cows

### PR DESCRIPTION
**Pull request by gama-A**
# Overview

This PR cowMarket price is correctly displayed on the playPage. numOfCows variable has been added to the userCommons entity and is correctly displayed on the playPage. 

# Issues Addressed

#14 Part of this issue is addresses the following PR will be to properly implement the buy and sell functionality to properly update number of cows for a user.

### CODE REVIEW

**Comment by gama-A** [comment]
@bzamora020

**Review by ryanmosalem — DISMISSED** [review]
LGTM

**Review by btk5h — DISMISSED** [review]
Please remove the `.DS_Store` file from your PR.

**Review by btk5h — CHANGES_REQUESTED** [review]
Please remove the .DS_Store file from your PR.

**Comment by gama-A** [comment]
> Please remove the .DS_Store file from your PR.

I have removed the file and pushed my changes, will ping you on slack when all checks are finished again.

**Comment by pconrad** [comment]
image

Not a good idea to push code that doesn't compile to a branch and then do a Pull Request....

**Review by pconrad — APPROVED** [review]
LGTM... as long as it works on Heroku.  I'll try deploying it

**Comment by bzamora020** [comment]
When ran on Heroku, the play page does not work as expected. 

image

**Comment by johnsonlin2001** [comment]
> When ran on Heroku, the play page does not work as expected.
> 
> image
@bzamora020 
I rebuilt the tables on heroku and I believe the playpage should show up now.
Screen Shot 2022-03-11 at 1 42 52 PM

**Comment by andrewhlu** [comment]
Hi all, I'm trying to deploy this branch to your 6pm-4-qa deployment so I can test out the play page, but I can't log in to your app due to a redirect URI mismatch. Could you all fix that?

**Comment by johnsonlin2001** [comment]
> 

I believe 6pm-3-qa should allow logins now. The playpage also shows up on the qa deployment.

**Comment by johnsonlin2001** [comment]
> > 
@andrewhlu 
 I believe 6pm-3-qa should allow logins now. The playpage also shows up on the qa deployment.

**Pull request merged**
