### PR TITLE
Buy and Sell endpoints with tests

### PR DESCRIPTION
**Pull request by eambriz27**
# Overview

In UserCommonsController.java, endpoints for Buy and Sell buttons have been added. When the Buy endpoint is called, the Total Wealth decreases by Cow Price, and the number of cows increases by one. When the Sell endpoint is called, the Total Wealth increases by Cow Price, and the number of cows decreases by one.

The UserCommonsControllerTests.java file now contains tests for these two endpoints and all backend tests pass. Tests include: buying/selling a cow when commons exists, buying/selling a cow when the commons for user does not exist, buying/selling a cow when the commons does not exist, and finally tests the edge cases of buying a cow when you do not have enough money (you will not be able to) or attempting to sell a cow when you have none (you will not be able to).

Note that if you do not set the total wealth and number of cows through Swagger to numbers specified in the Testing Plan, they will be initialized to 0 and you will be unable to do anything -- this will be addressed in a separate PR which will edit the CommonsController.java file.

# Issues Addressed

This PR addresses issues #14 an #15. Also starts and completes issue #49.

# Details

Current Commons (2 Cows, Total Wealth = $80, Market Cow Price: $20)
image

Buy One Cow Endpoint Working in Swagger:

image

Total Wealth and NumOfCows updated on Play Page:

image

Sell One Cow Endpoint Working in Swagger:
image

Total Wealth and NumOfCows updated on Play Page:

image

# Testing Plan

1. Create and join a commons.
2. On swagger-ui, go to the buy endpoint. Fill out all ids with 1. Set the total wealth to a number greater than 10 and the number of cows to a number greater than 1. Then, execute and notice that on the webpage, the total wealth and number of cows changes accordingly. 
3. Do the same for the sell endpoint.
4. Note that if you attempt to sell a cow but have no cows you will be unable to, and that you will be unable to buy a cow if your total wealth is $0. If you do not set the total wealth and number of cows to numbers specified above, they will be initialized to 0 and you will be unable to do anything -- this will be addressed in a separate PR which will edit the CommonsController.java file.

### CODE REVIEW

**Review by gama-A — DISMISSED** [review]
LGTM, thank you for fixing my mistake

**Review by Lin2 — APPROVED** [review]
LGTM

**Review by andrewhlu — APPROVED** [review]
LGTM, tested on Heroku. Will merge pending successful run of frontend mutation testing (which should pass since there are no frontend changes here).

**Comment by andrewhlu** [comment]
Unsure of why the checks are being listed as "not successful"... I can see that all checks passed (and I watched all of them run). This should be good to merge.

**Pull request merged**
