### PR TITLE
jc - Integrate issues from `starter`.

### PR DESCRIPTION
**Pull request by jacksoncooper**
We're missing the following.

- `30-no-toasts-when-not-loggedin`

### CODE REVIEW

**Review by DannyCoco — APPROVED** [review]

**Review by sytarno — COMMENTED** [review]
That's true. We are missing a markdown file.

**Review by sytarno — APPROVED** [review]

**Review by kheff16 — APPROVED** [review]
Looks great!

**Review by sahilnaik1 — APPROVED** [review]

**Comment by jacksoncooper** [comment]
@kheff16 Are you able to merge to `main` now?

**Comment by kheff16** [comment]
Up to you guys to merge it after the review @jacksoncooper

that way if you make changes you can modify before merging

**Pull request merged**
